export {default as Footer} from './Footer'
export {default as Footer5} from './Footer5'
export {default as Footer4} from './Footer4'
export {default as Footer3} from './Footer3'
export {default as Footer2} from './Footer2'
export {default as Footer1} from './Footer1'